### ISSUE TITLE
Updates post adding

### ISSUE THREAD

**Issue by StuShepherdUK** [Gradiant/dockerized-kibana#3]
Good afternoon, loving this plugin for changing Kibana thank you...

I have added it onto my v7.0.0, but i am struggling to then change some of the features...

i.e. i have run kibana-plugins remove gradiant_style...

updated the kibana\gradiant_style\public\less\main.less , changing the colour codes from red to grey...

repackaged the zip file and re-run, kibana-plugins install file:///d:\gradiant_style.zip

Installs okay but kibana is still displaying red.  Have tried a different browser type incase the css was saved but still red.   Am i missing something ?

Also, is there anything i need to do specific when i want to play with the icons?  i.e. the hex/binary placed into the kibana files, is the information available anywhere so that i can play with that side and have custom logo's ?  

Thank you again,

**Comment by cgiraldo** [comment]
The main.less file should be compiled to bundles/gradiant_style.style.css.

Check if your kibana server is serving bundles/gradiant_style.style.css with your modifications.

If not remove the optimize/bundles/gradiant_style.style.css file and restart kibana.

We have not customized the icons since it is not as direct as the rest of the css atributes. If you find the way to customize them, contributions are welcome! ;)
